language: go
go:
  - tip
install:
  - go get github.com/astaxie/beego
script:
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=amd64 GOOS=linux go build -ldflags="-s -w"  && tar czvf ifconfig-linux-amd64.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=386 GOOS=linux go build -ldflags="-s -w"  && tar czvf ifconfig-linux-x86.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=arm GOARM=5 GOOS=linux go build -ldflags="-s -w"  && tar czvf ifconfig-linux-armv5.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=arm GOARM=6 GOOS=linux go build -ldflags="-s -w"  && tar czvf ifconfig-linux-armv6.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=arm GOARM=7 GOOS=linux go build -ldflags="-s -w"  && tar czvf ifconfig-linux-armv7.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=arm64 GOOS=linux go build -ldflags="-s -w"  && tar czvf ifconfig-linux-arm64.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=ppc64 GOOS=linux go build -ldflags="-s -w"  && tar czvf ifconfig-linux-ppc64.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=ppc64le GOOS=linux go build -ldflags="-s -w"  && tar czvf ifconfig-linux-ppc64le.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=mips64 GOOS=linux go build -ldflags="-s -w"  && tar czvf ifconfig-linux-mips64.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=mips64le GOOS=linux go build -ldflags="-s -w"  && tar czvf ifconfig-linux-mips64le.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=amd64 GOOS=darwin go build  && tar czvf ifconfig-darwin-amd64.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=amd64 GOOS=windows go build  && tar czvf ifconfig-windows-amd64.tar.gz ifconfig.exe views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=386 GOOS=windows go build  && tar czvf ifconfig-windows-x86.tar.gz ifconfig.exe views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=amd64 GOOS=freebsd go build  && tar czvf ifconfig-freebsd-amd64.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=386 GOOS=freebsd go build  && tar czvf ifconfig-freebsd-x86.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=arm GOOS=freebsd go build  && tar czvf ifconfig-freebsd-arm.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=amd64 GOOS=openbsd go build  && tar czvf ifconfig-openbsd-amd64.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=386 GOOS=openbsd go build  && tar czvf ifconfig-openbsd-x86.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=amd64 GOOS=netbsd go build  && tar czvf ifconfig-netbsd-amd64.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=386 GOOS=netbsd go build  && tar czvf ifconfig-netbsd-x86.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=arm GOOS=netbsd go build  && tar czvf ifconfig-netbsd-arm.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=amd64 GOOS=dragonfly go build  && tar czvf ifconfig-dragonflybsd-amd64.tar.gz ifconfig views static conf
  - env GOPATH=$GOPATH:$PWD/../.. GOARCH=amd64 GOOS=solaris go build  && tar czvf ifconfig-solaris-amd64.tar.gz ifconfig views static conf
env:
  global:
  - GITHUB_REPO: missdeer/ifconfig
  - GIT_NAME: missdeer
  - GIT_EMAIL: missdeer@dfordsoft.com
  - secure: Putn2dfCb7wEXFZ5yF/TFo8HHiyIGf7b80C5lJHB4YTKxKBic8xOd3v6IhVfXNZgHSvuA+TVDI9VQJ9eRviJalCVN1qP88oLlrj4/q1WeF9DDUxpTPHV1uP/z6F8s0nmyICRFPs7Gq0fUyfZae+DgF0uaZT+6VxDksjg25eYFFQ=
deploy:
  provider: releases
  api_key:
    secure: enWM7VXzmCT9NwUbtGPq4uQ+9MOV7SHc+BLWrUzRVxBBveVb0w1uHVOveaHhgd8sW9fdwM/QhgXu4xl5Jet3iJ+r+7pU6yAQmurKfe9iH1VYg0HOE/cl3KHsjarbgjhJ4jDtcaOnqauJbdAIKrY2KEcgp4uXZcTv2spvIBvRhZ4=
  file: 
    - ifconfig-darwin-amd64.tar.gz           
    - ifconfig-dragonflybsd-amd64.tar.gz     
    - ifconfig-freebsd-amd64.tar.gz          
    - ifconfig-freebsd-arm.tar.gz            
    - ifconfig-freebsd-x86.tar.gz            
    - ifconfig-linux-amd64.tar.gz            
    - ifconfig-linux-arm64.tar.gz            
    - ifconfig-linux-armv6.tar.gz            
    - ifconfig-linux-armv7.tar.gz            
    - ifconfig-linux-mips64.tar.gz           
    - ifconfig-linux-mips64le.tar.gz         
    - ifconfig-linux-ppc64.tar.gz            
    - ifconfig-linux-ppc64le.tar.gz          
    - ifconfig-linux-x86.tar.gz              
    - ifconfig-netbsd-amd64.tar.gz           
    - ifconfig-netbsd-arm.tar.gz             
    - ifconfig-netbsd-x86.tar.gz             
    - ifconfig-openbsd-amd64.tar.gz          
    - ifconfig-openbsd-x86.tar.gz            
    - ifconfig-solaris-amd64.tar.gz                
    - ifconfig-windows-amd64.tar.gz              
    - ifconfig-windows-x86.tar.gz                
  on:
    repo: dfordsoft/ifconfig
    tags: true
  skip_cleanup: true
